### ISSUE TITLE
Check text on stdin

### ISSUE THREAD

**Issue by dpc** [convco/convco#100]
**Is your feature request related to a problem? Please describe.**

I'd like to check the commit message in `commit-msg` git hook, which ideally would just invoke `echo "$1" | convco check --stdin` or something like that.

Yes, I know there's `convco commit` but not everyone will necessarily use it in my team, while git hooks are set up automatically.

**Describe the solution you'd like**
`echo "$1" | convco check --stdin` should validate the input.

**Describe alternatives you've considered**
Joining monastery and dedicating my life towards study of scriptures and meditation.

**Additional context**
That's really all I have. Thank you for making this project.

**Comment by hdevalke** [comment]
Thank you for the suggestion. I added it in db1c946ae29b9737946a939dcc4e516ce05da80c.
I will release soon.

It works without providing an extra argument:

```
❯ git log -1 --format=%B | cargo run -q -- check && echo $?
0
❯ cargo run -q -- check <<< bad || echo $?
first line doesn't match `<type>[optional scope]: <description>`
1
❯ cargo run -q -- check
FAIL  38be02d  wrong type: doc  doc: clarify cmake is needed to build
FAIL  8c4dbb6  wrong type: doc  doc: improve gitlab section in `README.m...
FAIL  ffcf34a  scope does not match regex: changelog|check|commit|version  ci(docker): Add a dockerfile
FAIL  724bb2b  first line doesn't match `<type>[optional scope]: <description>`  release v0.3.0
FAIL  155e652  scope does not match regex: changelog|check|commit|version  build(deps): bump versions

5/166 failed
```

**Comment by dpc** [comment]
Thank you!
