### ISSUE TITLE
`changelog` produces `vUnreleased` instead of `Unreleased` heading

### ISSUE THREAD

**Issue by ite-klass** [convco/convco#101]
In v0.3.12 changelog produced the *unreleased* headline `Unreleased`, now in v0.3.13 it produces a `vUnreleased` headline.

Is this an intentional change?

Unreleased is not a version. Prefixing it with v is surprising and confusing, and IMO wrong.

**Comment by hdevalke** [comment]
Thanks for notifying.
This is indeed not intentional. I will fix this soon
