### ISSUE TITLE
quit part way through `convco commit` 

### ISSUE THREAD

**Issue by rbuckland** [convco/convco#113]
**Describe the bug**
inside a `convco commit` after selection of a type, in the field for entering "scope", or the next "description"
you cannot exit (cancel) with `^C` or `^D` 

**To Reproduce**
```
❯ convco commit
✔ type · feat
? scope () › ^C^C^C^C^C
```

**Expected behavior**
The ability to `Control-C` quit part way through

**System (please complete the following information):**
 - OS: [ubuntu]
 - Version: [22.04]

**Workaround**
1. open new terminal and `killall convco` ; or
2. background and kill
  ```
  ❯ convco commit
  ✔ type · fix
  ? scope () › ^Z
  zsh: suspended  convco commit

  ✦ ❯ jobs
  [1]  + suspended  convco commit
  
  ✦ ❯ kill %1
  [1]  + terminated  convco commit     
   ```

**Comment by hdevalke** [comment]
This is probably related to a change in the dependency dialoguer, or a transient dependency of it, but i can't find a solution right now.

**Comment by hdevalke** [comment]
It works again when i remove the code introduced here: https://github.com/convco/convco/pull/33/files#diff-bf1e66c5bdfc412eccacf65e5e9734bc1998fdbfc8a06a5f12c5538a66027cceR183

But the cursor is then hidden again, when pressing CTRL-C when selecting the commit type.
