### ISSUE TITLE
Ignore leading comments and empty lines when parsing commit via stdin

### ISSUE THREAD

**Issue by dpc** [convco/convco#114]
**Is your feature request related to a problem? Please describe.**
I just implemented `commit-msg` git hook linting with `convco`: https://github.com/fedimint/fedimint/pull/1573/files

I had to do some extra work, because the commit message can actually be prefixed with newlines and comment lines which git will happily throw away before turning the whole message into a actual commit, but `convco` will complain about.

**Describe the solution you'd like**
Not sure if should be the default behavior altogether, or just when parsing from stdin, or maybe an option, but it would be easier if `convco` could take care of it (ignore leading newlines and comments).

**Comment by hdevalke** [comment]
`convco` does this in the `commit` subcommand. And it looks like this is documented in git:

> The commit-msg hook takes one parameter, which again is the path to a temporary file that contains the commit message written by the developer. 

as this repository follows conventional commits, comments and extra newlines should be seen as an error, so i think the best way is to add a flag `--ignore-newlines-and-comments`

**Comment by hdevalke** [comment]
The behaviour of git can depend on the [`--cleanup`](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---cleanupltmodegt) mode.

**Comment by dpc** [comment]
`-ignore-newlines-and-comments` gets long and without "leading" a bit incorrect, so maybe `--cleanup` instead as well? :D

**Comment by hdevalke** [comment]
I used `--strip` other modes can be implemented later.

**Comment by hdevalke** [comment]
fixed in #116
