### ISSUE TITLE
pre-push docs example doesn't work

### ISSUE THREAD

**Issue by ckoehler** [convco/convco#117]
**Describe the bug**

The pre-push example on https://convco.github.io/check/ doesn't work, because: 

1. `convco` can't just check one commit (see #18). 
2. (with the above fixed,) pushing a new branch would only check the latest commit, not all of them

**To Reproduce**
1. Create a new branch
2. Make 2 or more commits
3. Push

**Expected behavior**
All 2+ commits are checked

**Comment by hdevalke** [comment]
Which version of convco are you using?

7840b8a2888f1b83dcd93f7446b03246d28542c2 should check all commits as it will only read from stdin a single message if no revision or range is given.

If only a single revision is given all parent commits starting including itself will be checked.

I try to reproduce this later

**Comment by ckoehler** [comment]
I am using 0.3.15. I don't think the problem is the app, but the docs. The way the pre-push hook works it only gives you one commit, the last, so convco only checks that one commit (as expected). The problem is that the docs make it sound like it's checking all the commits from a new branch, when it's not.

**Comment by hdevalke** [comment]
> so convco only checks that one commit (as expected)

This did not work

```
❯ convco check 23cd8cf; echo $?
the given reference name '23cd8cf' is not valid; class=Reference (4)
1
```

#118 fixes this. I could not replicate the issue where a single commit will only check 1 commit. it always checks the commit and all parents from it.
To check a single revision you should use a range e.g. "<sha1>^..<sha1>"

**Comment by hdevalke** [comment]
I made a test. With convco 3.15:

```
❯ git push upstream HEAD:a
the given reference name '60ad33c79353a6af1fdcc547b4781a6a4a3cfb31' is not valid; class=Reference (4)
error: failed to push some refs to 'github.com:convco/convco.git'
```

with this change

```
❯ git push upstream HEAD:a
FAIL  60ad33c  empty commit message  
FAIL  379b055  empty commit message  
FAIL  38be02d  wrong type: doc  doc: clarify cmake is needed to build
FAIL  8c4dbb6  wrong type: doc  doc: improve gitlab section in `README.m...
FAIL  ffcf34a  scope does not match regex: changelog|check|commit|version  ci(docker): Add a dockerfile
FAIL  724bb2b  first line doesn't match `<type>[optional scope]: <description>`  release v0.3.0
FAIL  155e652  scope does not match regex: changelog|check|commit|version  build(deps): bump versions

7/182 failed
error: failed to push some refs to 'github.com:convco/convco.git'
```

**Comment by hdevalke** [comment]
closed by #118

**Comment by ckoehler** [comment]
Thanks, let me try it out!

**Comment by hdevalke** [comment]
Yes indeed, i had the same issue when releasing, there are 5 non-conventional commits.
However, the example can be tweaked and do something else if there is a new branch e.g. using `range="origin/main..$local_sha"` or use a `--limit 20` 

Maybe an `--exclude <rev>` flag could be added to exclude some commits or ranges, but i think there are easier alternatives to exclude older non-conventional commits.

**Comment by ckoehler** [comment]
Oh, I didn't think to just compare to `origin/main`; that'll work! Thanks again!
