### ISSUE TITLE
git commit --fixup with convco

### ISSUE THREAD

**Issue by garyray-k** [convco/convco#127]
**Describe the bug**
When using the `--fixup` flag for `git commit`, convco check identifies the fixup commit as a bad commit. As a built-in git feature, I would expect this feature to work as expected. Specifically, the workflow described [here](https://blog.sebastian-daschner.com/entries/git-commit-fixup-autosquash) is useful. [--fixup docs](https://git-scm.com/docs/git-commit/2.32.0#Documentation/git-commit.txt---fixupamendrewordltcommitgt)

**To Reproduce**
1.  `git init`
2. `touch file`
3. `git add file`
4. `git commit -m "feat: first commit"`
5. `convco check` (no issues)
6. Edit `file`
7. `git add file`
8. `git commit -a --fixup <first commit hash>`
9. `convco check` should give you
```
FAIL  5778242  first line doesn't match `<type>[optional scope]: <description>`  fixup! feat: first commit

1/2 failed
```

**Expected behavior**
convco passes a check with this style of commit message.

**System (please complete the following information):**
 - OS: MacOS
 - Version: 13.3.1

**Additional context**
I believe there are other git commit prefixes of similar nature, but only encountered this issue.
This was encountered in the [`fedimint` repo](https://github.com/fedimint/fedimint) where convco check is part of our git commit hooks.

**Comment by hdevalke** [comment]
Convco follows [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/).
Fixups don't follow it. 

We could add an `--allow-fixup` flag, but imho one should avoid to merge it to the main branch as the main purpose is to use it with auto squash.

**Comment by garyray-k** [comment]
Fair. I ended up using `--no-verify` to circumvent the issue before rebasing with the auto squash.

**Comment by hdevalke** [comment]
This could be done using the `--strip-prefix` option https://github.com/convco/convco/issues/133 (still to be released).

**Comment by f1rstlady** [comment]
> This could be done using the `--strip-prefix` option [#133](https://github.com/convco/convco/issues/133) (still to be released).

@hdevalke I set the regex through `stripRegex: '(fixup|squash)! '` in the config file, yet it does not work. What am I doing wrong?
