### ISSUE TITLE
option to ignore first commit on check

### ISSUE THREAD

**Issue by bluebrown** [convco/convco#132]
**Is your feature request related to a problem? Please describe.**

I have trouble using the `check` command because usually my initial commit doesn't follow conventional commits. 

**Describe the solution you'd like**
It would be nice to be able to ignore that and only check subsequent commits. 

**Describe alternatives you've considered**
Use a conventional commit message for the first commit

**Comment by hdevalke** [comment]
There is an option `--max-count` that can be used to limit how much commits are checked.

The other alternative could be to use the initial commit as  

```
❯ git commit --allow-empty -m 'first commit'
[main (root-commit) a495ad2] first commit

❯ git commit --allow-empty -m 'fix: second commit'
[main d09d6b0] fix: second commit

❯ convco check
FAIL  a495ad2  first line doesn't match `<type>[optional scope]: <description>`  first commit

1/2 failed

❯ convco check a495ad2..HEAD
no errors in 1 commit
```

You can get the root commit by using this command `git rev-list --max-parents=0 HEAD`. In a bash script you could use `convco check $(git rev-list --max-parents=0 HEAD)..HEAD`
