### ISSUE TITLE
Option to strip a given prefix pattern from commit message before determining the version

### ISSUE THREAD

**Issue by bluebrown** [convco/convco#133]
**Is your feature request related to a problem? Please describe.**
Azure DevOps, by default, prefixing squash merge commits with `Merged PR <n>:` and puts the user provided message after the colon. This leads to technically non conventional commit compliant commits. 

**Describe the solution you'd like**
It would be neat to be able to give convco a regex pattern that it should strip before looking at commit messages. This would allow keeping using azures default message

So for example, on a commit message like `Merge Pr 4: feat: my cool feature`, we could ignore the merge prefix `Merge PR 4: ` by providing a regex pattern. Perhaps `concvo version --strip-prefix 'Merge PR \d+\s+'`

**Describe alternatives you've considered**
As an alternative solution, it is actually possible to change the behavior of azure but users had to remember to take extra steps on every merge. It would also remove the information about the merge, which may not be desired.

**Additional context**
The behavior of Azure DevOps is described here https://learn.microsoft.com/en-us/azure/devops/repos/git/complete-pull-requests?view=azure-devops&tabs=browser#complete-a-pull-request

**Comment by hdevalke** [comment]
There is an option (iirc enabled by default) to not check merge commits. If all others commits are conventional the merge commit can be ignored as it does not add any value in the calculation of the version.

**Comment by bluebrown** [comment]
Hi, thanks for the swift response! 

The problem with that is that it will be the only commit landing in main since we do squash merge strategy. 

We do this in order to keep a lean history and also enhance DX, since the devs do not need to follow conventional commits while working on their feature branch. Only the squash merge commit follow conventional commits.

**Comment by hdevalke** [comment]
I don't have the time right now to implement this, but here are some starting points if somebody would take this:

- https://github.com/convco/convco/blob/master/src/conventional/commits.rs#L121 to add a prefix regex
- https://github.com/convco/convco/blob/master/src/conventional/commits.rs#L136 strip the line here

it could either be added to the [config](https://github.com/convco/convco/blob/master/src/conventional/config.rs#L31) and/or as an option in the [cli](https://github.com/convco/convco/blob/master/src/cli.rs) for `check`, `changelog`, `version`.

**Comment by bluebrown** [comment]
I havent worked with rust yet, but Ill give it a shot. Thanks You.
