### ISSUE TITLE
`convco check --from-stdin` has zero exit code on failure

### ISSUE THREAD

**Issue by lukany** [convco/convco#140]
**Describe the bug**
`convco check --from-stdin` has zero exit code on failure.

**To Reproduce**
Example command in shell that demonstrates the bug:
```
> echo "unconventional commit" | convco check --from-stdin; echo $?
FAIL  -  first line doesn't match `<type>[optional scope]: <description>`  unconventional commit
0
```

**Expected behavior**
The command should have a non-zero return code.

**System:**
 - OS: macOS
 - Version: 13.4.1 (c)

**Additional context**
Command `convco check` has a non-zero return code when it fails. The behaviour of `convco check --from-stdin` is thus inconsistent.

**Comment by hdevalke** [comment]
Indeed, it should return an error here in case the match is false: https://github.com/convco/convco/blob/master/src/cmd/check.rs#L91
