### ISSUE TITLE
v0.4.1 --from-stdin regression 

### ISSUE THREAD

**Issue by yurrriq** [convco/convco#142]
**Describe the bug**

v0.4.1 no longer exists with a nonzero status code when given an invalid commit message via `--from-stdin`

**To Reproduce**
```bash
$ echo 'bad commit message' | convco check --from-stdin
FAIL  -  first line doesn't match `<type>[optional scope]: <description>`  bad commit message
$ echo $?
0
```

**Expected behavior**

```bash
$ echo 'bad commit message' | convco check --from-stdin
FAIL  -  first line doesn't match `<type>[optional scope]: <description>`  bad commit message
$ echo $?
1
```

**System (please complete the following information):**
 - OS: [e.g. ubuntu] Ubuntu
 - Version: [e.g. 19.10] 22.04 LTS

**Additional context**

Works as expected with convco v0.4.0. At a glance, I suspect https://github.com/convco/convco/pull/137

**Comment by hdevalke** [comment]
Thank you for reporting, but I think this is fixed by https://github.com/convco/convco/pull/141. But it is not released yet.

**Comment by yurrriq** [comment]
Great, thanks! Any timeline on the next release? It's currently broken in NixOS/nixpkgs@master and I'd love to bump there.

**Comment by hdevalke** [comment]
I'll do my best to find time this weekend.

**Comment by hdevalke** [comment]
Done.

**Comment by hdevalke** [comment]
#143 created in order to improve releasing a new version.
