### ISSUE TITLE
bug: `convco commit` allows invalid scopes

### ISSUE THREAD

**Issue by cafkafk** [convco/convco#145]
**Describe the bug**
`convco commit` allows committing with an invalid scope.

From conventional commits:
> 4. A scope MAY be provided after a type. A scope MUST consist of a noun describing a section of the codebase surrounded by parenthesis, e.g., `fix(parser)`:

![2023-09-18_18-45](https://github.com/convco/convco/assets/89321978/bd85ea92-1c01-415d-b238-13612a3371b8)

**To Reproduce**
*not relevant*

**Expected behavior**
Convco should not allow spaces in scopes, as that would make the scope not a noun which it MUST be.

**System (please complete the following information):**
 *not relevant*

**Additional context**
None I can think of.

**Comment by cafkafk** [comment]
I suspect it might be this regex that would have to be changed https://github.com/convco/convco/blob/81f59f1e539ca2b4dbf449713ca85969027adf16/src/conventional/commits.rs#L240

**Comment by cafkafk** [comment]
> You could change the regex in the config file. The regex is allowing dashes, slashes and underscores, but not spaces.

Would you want me to PR this or just fix it locally?

**Comment by hdevalke** [comment]
A PR is nice, I can confirm that it is the issue, but a local fix will be faster, unless you build your own binary from it.

```
❯ convco check -c <(cat <<< 'scopeRegex: "^[[:alnum:]]+(?:[-_/][[:alnum:]]+)*$"') --from-stdin <<< 'chore(a b): bump deps'; echo $?
could not find repository from '.'; class=Repository (6); code=NotFound (-3)
FAIL  -  scope does not match regex: ^[[:alnum:]]+(?:[-_/][[:alnum:]]+)*$  chore(a b): bump deps
1

~ 
❯ convco check -c <(cat <<< 'scopeRegex: "[[:alnum:]]+(?:[-_/][[:alnum:]]+)*"') --from-stdin <<< 'chore(a b): bump deps'; echo $?
could not find repository from '.'; class=Repository (6); code=NotFound (-3)
0
```

**Comment by hdevalke** [comment]
@cafkafk I did create a PR, if the checks are green I will merge this soon. But I won't have the time to create a release this week.

**Comment by Hoverbear** [comment]
@hdevalke any chance you're planning to cut a release with this fix soon? It would be nice to include this fix in nixpkgs without going to an unstable version.

**Comment by hdevalke** [comment]
I will release it this evening.

**Comment by hdevalke** [comment]
@Hoverbear [v0.4.3](https://github.com/convco/convco/releases/tag/v0.4.3) has been released.

**Comment by Hoverbear** [comment]
Thanks so much!
