### ISSUE TITLE
Consider warning user if `convco commit` is run without any staged files

### ISSUE THREAD

**Issue by cafkafk** [convco/convco#146]
**Is your feature request related to a problem? Please describe.**
It's very frustrating when I run `convco commit`, type all the fields, only to find that I didn't stage any files with `git add`.

**Describe the solution you'd like**
I would prefer if `convco commit` printed a warning to the screen, informing me that I haven't staged any files.

**Describe alternatives you've considered**
I've thought that it could be automated, but that would be hard to do in a way that everyone likes, and a lot more work than just a warning that solves the most frustrating part.

**Additional context**
I don't have any.

**Comment by hdevalke** [comment]
At the moment convco commit is indeed building up the commit message, and then executing the git cli.

You could use `convco commit -- -a` to add all files.

Quick solution could be that we run `git add -N` and `git add -p` before, such that you can add the changes that are needed.

**Comment by hdevalke** [comment]
I made PR #148 to add `git add -N .` and `git add -p` to be run before showing the wizard and running `git commit ..`

**Comment by cafkafk** [comment]
Awesome, can't wait for this to be merged!

**Comment by hdevalke** [comment]
#151 adds the options --intent-to-add and --patch. This will disable the behavior to automatically do it, but you will be able to use environment variables to override the defaults.
