### ISSUE TITLE
`version` is not working properly on `prerelease`

### ISSUE THREAD

**Issue by kaankoken** [convco/convco#149]
**Describe the bug**

I think `version` is not `bump` prerelease versions correctly & does not display the correct `current` version as well.

**To Reproduce**
1. I have started the tag with `v0.2.2`. 
2. I commit a some changes that does not in the convention.
3. Then, I used `convco` to  get next `prerelease`:

```bash
echo "version=$(convco version --bump --prerelease rc)" >> "$GITHUB_OUTPUT"
# version  `v0.2.2-rc.1`
```
4. I tag the commit with the given new `prelease` tag. Also, I run `version`
```bash
# Current version is not correct, should be v0.2.2-rc.1
convco version # v0.2.2
``` 
5. I add a commit `fix: test`
6. I run the command again on `step 3`

```bash
# version `v0.2.3-rc.1`
```

7. I repeated `step-3 & step-4` with a new commit `fix: test1`

```bash
# Result again is same
# version `v0.2.3-rc.1`
```
Also run the. `version` again.
```bash
# Current version is still not correct, should be v0.2.3-rc.1
convco version # v0.2.2
``` 

**Expected behavior**
I was excepting to bump a version as `v0.2.2-rc.2`, `v0.2.2-rc.3` not as a new version & not bumping at all.
Also **current version** should change as well.

**System (please complete the following information):**
 - OS: MacOS, Ubuntu
 - Version: 13.4.1, 22.04

**Additional context**
![image](https://github.com/convco/convco/assets/28218396/5a8518b4-16f5-4db6-a971-71187cb92703)

**Comment by hdevalke** [comment]
I have to test this out.

I think there is a bug that when there is a tag v0.2.2 the bump pre-release should always be 0.2.3-rc.1 or 0.3.0-rc1.

I am not sure what should be the behavior if there are no fix/feat or breaking changes.

**Comment by kaankoken** [comment]
Is there a way to add/introduce custom config so that parse other commits used as patch/minor/major?

**Comment by hdevalke** [comment]
> Additional types are not mandated by the Conventional Commits specification, and have no implicit effect in Semantic Versioning (unless they include a BREAKING CHANGE)

Not implemented as not in the spec.

**Comment by hdevalke** [comment]
Sorry to answer late, but i don't have much free time. 
I see indeed that it does not do what is expected.

```

**Comment by hdevalke** [comment]
I think that in this case the issue is that there is no commit that increments the version by convention.
Maybe in this case, there should exit with an error, or it should bump to the next patch release?

**Comment by hdevalke** [comment]
For point 7 I cannot reproduce. 
Which version of convco do you use @kaankoken ?

```
#!/bin/env sh
set -x
rm -rf .git
convco version
git init .
convco version
git commit --allow-empty -m 'hotfix: correct ..'
convco version
git tag v0.2.2
convco version
git commit --allow-empty -m 'chore: release'
git commit --allow-empty -m 'perf: use precompiled binary'
convco version --bump --prerelease rc
git tag "v$(convco version --bump --prerelease rc)"
convco version
git commit --allow-empty -m 'fix: test'
convco version --bump --prerelease rc
git tag "v$(convco version --bump --prerelease rc)"
git commit --allow-empty -m 'fix: test'
convco version
```

The last command prints `0.2.3-rc.1` as expected.

**Comment by taorepoara** [comment]
I think this has been fixed. @kaankoken can you re-try your use case ?
