### ISSUE TITLE
Failed to run `cargo install convco`.

### ISSUE THREAD

**Issue by qixiaoo** [convco/convco#15]
**Describe the bug**
When I run `cargo install convco` to install convco, the following error occurred.

```
➜  ~ cargo install convco
    Updating `https://mirrors.tuna.tsinghua.edu.cn/git/crates.io-index.git` index
  Downloaded convco v0.3.4 (registry `https://mirrors.tuna.tsinghua.edu.cn/git/crates.io-index.git`)
  Downloaded 1 crate (27.1 KB) in 2.80s
  Installing convco v0.3.4
error: failed to compile `convco v0.3.4`, intermediate artifacts can be found at `/var/folders/3v/92vgctp51576pfbydr3672g40000gn/T/cargo-installaXxrnQ`

Caused by:
  failed to select a version for the requirement `zeroize = "^0.9.3"`
  candidate versions found which didn't match: 1.3.0, 1.2.0, 1.1.1, ...
  location searched: `https://mirrors.tuna.tsinghua.edu.cn/git/crates.io-index.git` index (which is replacing registry `https://github.com/rust-lang/crates.io-index`)
  required by package `dialoguer v0.7.1`
      ... which is depended on by `convco v0.3.4`
  perhaps a crate was updated and forgotten to be re-vendored?
```

**To Reproduce**
1. open terminal
2. run `cargo install convco`

**Expected behavior**
Convco should be installed.

**System (please complete the following information):**
 - OS: macOS Catalina
 - Version: 10.15.7

**Additional context**
I think this is the same issue as [this one](https://github.com/sdttttt/gcr/issues/63).

**Comment by hdevalke** [comment]
Thanks for reporting.

You can try to install using `cargo install convco --locked`
I will bump the dependencies and do a new release, but that could take some time.

**Comment by hdevalke** [comment]
I will release 0.3.5 soon
