### ISSUE TITLE
Default YAML file unavailable

### ISSUE THREAD

**Issue by trueNAHO** [convco/convco#154]
The link to the default YAML file is invalid:

https://github.com/convco/convco/blob/252c13663839b2658c9a4090a67d3b160492ea07/README.md?plain=1#L41

**Comment by hdevalke** [comment]
It should be linked to the default configuration here: https://convco.github.io/configuration/. The page probably needs to be updated

**Comment by hdevalke** [comment]
The readme has been updated. Thank you!
