### ISSUE TITLE
Display commit revision for latest Tag, or first commit

### ISSUE THREAD

**Issue by rbuckland** [convco/convco#156]
I am integrating convco into a monorepo that uses pants for the build of many artefacts (packages)

Pants, given a commit can detail with filters (paths, types) which packages are impacted.

It can also build the said packages with the same filters.

An example of the usage would be 

-----
pants --changes-since=$(convco version --tagrev --prefix my/lib/v --paths my/lib ) package list
-----

Convco knows for a given paths (path/to/package) and for a given tag prefix path/to/package/v , what the latest tag is.

What I am looking for is to ask convco for the commit of that tag instead  (version --tagrev)

Currently I do this lookup in shell with calls to convco and to git log

It will be nice to do this only with convco

In scenario where there is no tag then convco should print the first introducing commit (if paths or the first commit if no paths)

Thoughts ?

**Comment by hdevalke** [comment]
I used `--commit-sha` in #158 , but i think it might work to add a flag `--print-prefix` as pants probably understands all kinds of [git revisions](https://git-scm.com/docs/gitrevisions) for `--changed-since`

this is what it prints for this repository at e9d98f7ee3b1c08242b694afdd7c2712994d3e7b.

```
❯ git log --oneline -1 v0.4.3
feeea90 (tag: v0.4.3) chore: release v0.4.3

❯ cargo run -- version
    Finished dev [unoptimized + debuginfo] target(s) in 0.07s
     Running `target/debug/convco version`
0.4.3

❯ cargo run -q -- version
0.4.3

❯ cargo run -- version --commit-sha
    Finished dev [unoptimized + debuginfo] target(s) in 0.06s
     Running `target/debug/convco version --commit-sha`
feeea9022f2795d280602aaba4d3c24a8088f125
```

**Comment by hdevalke** [comment]
I also added an option to print the prefix `convco version --print-prefix` or `convco version --pp`

**Comment by rbuckland** [comment]
Very nice. Thanks !
