### ISSUE TITLE
[FEAT] Support path globs for `convco version --path`

### ISSUE THREAD

**Issue by brooksmtownsend** [convco/convco#160]
**Is your feature request related to a problem? Please describe.**
I work in a large Rust monorepo [wasmCloud](https://github.com/wasmCloud/wasmCloud) and we've been using conventional commits for quite a while. I wanted to use this tool to be able to describe when I need to bump a version based on breaking changes, but I can't seem to specify the `--path` properly when computing version bumps. Either globbing isn't supported, or I'm specifying the file incorrectly.

**Describe the solution you'd like**

For example, I have a crate in the workspace called `wash-lib` that I want to release a new version of. There have been breaking changes in other crates that I don't want to consider in my new version bump, I only want to consider changed files in the `./crates/wash-lib` repository. Additionally, we tag each release with an easy prefix so I can easily filter back to the last tag cut. Here's what I want to run:
```
convco version --prefix wash-lib-v -P 'crates/wash-lib/*' --bump
```

This unfortunately doesn't detect a need to bump at all. However, the following command does properly detect a breaking change in a file:
```
convco version --prefix wash-lib-v -P 'crates/wash-lib/src/actor.rs' --bump
```

**Describe alternatives you've considered**
I considered adding some complex script to list out paths in commits and feed them to the convco tool, but this feature just seemed a lot better!

**Additional context**
If you are able to point me in a direction, I'm happy to contribute this feature 😄

**Comment by hdevalke** [comment]
Globbing is part of the shell, but adding [num_args](https://docs.rs/clap/latest/clap/builder/struct.Arg.html#method.num_args) is probably necessary to avoid repeating the `-P` option and be able to use globbing.

**Comment by hdevalke** [comment]
Depending on the shell you use there are some options to prefix e.g. in zsh you can use `path*(P:-P:)`
for other shells.
In you case it should work by just doing `convco version --prefix wash-lib-v -P crates/wash-lib --bump`

**Comment by brooksmtownsend** [comment]
```
convco version --prefix wash-lib-v -P crates/wash-lib --bump
```

This does work! I'm not exactly sure how I didn't stumble on this, maybe it was the `./` prefix?
```
~/github.com/wasmcloud/wasmCloud ➜ convco version --prefix wash-cli-v --paths ./crates/wash-cli --bump
0.24.1

~/github.com/wasmcloud/wasmCloud ➜ convco version --prefix wash-cli-v --paths crates/wash-cli --bump
0.25.0
```

**Comment by hdevalke** [comment]
The code used this to compare paths: https://github.com/convco/convco/blob/master/src/git.rs#L170

Maybe removing `./` in code or print a warning should be done.

**Comment by hdevalke** [comment]
Added documentation in the cli help message

**Comment by brooksmtownsend** [comment]
Thank you @hdevalke! I'm happy to consider this issue closed, as my original request to be able to specify an entire folder (not necessarily needing globs, was just an idea) is complete. I'll leave it to you if you'd like to close it now
