### ISSUE TITLE
Better Documentation for using convco as git editor

### ISSUE THREAD

**Issue by Nick1296** [convco/convco#162]
**Describe the bug**
Setting the git editor as `convco commit` doens't work 

**To Reproduce**
1. Install convco
2. Set core.editor as `convco commit` in git config
3. run git commit
4. convco commit complains that there is an unxepected argument, which is `path/to/repo/.git/COMMIT_EDITMSG`

**Expected behavior**
Convco commit should run and after done git should proceed with committing the files

**System (please complete the following information):**
 - OS: NixOS
 - Version: 23.11

**Additional context**
I am sure I am configuring something wrong, so maybe a little bit of clarification should be enough.

**Comment by hdevalke** [comment]
added an example how to use it.
I will release this weekend (or tonight).
Please open a new ticket if it still does not work with the new version
