### ISSUE TITLE
Unable to get `convco check` to check a single commit

### ISSUE THREAD

**Issue by BroderickCarlin** [convco/convco#18]
**Describe the bug**
Based on my understanding of the tool/project it should be possible to run `convco check` to check either a range of commits or a single commit. While checking a range of commits appears functional I have yet to be able to get the tool to be able to check a single commit, regardless of what type of commit-ish is used. 

**To Reproduce**
1. run `convco check commit-ish-here`
2. get `the given reference name 'commit-ish-here' is not valid; class=Reference (4)`

**Expected behavior**
Expected behavior is that the tool would verify the commit message of the specified commit-ish 

**System (please complete the following information):**
 - OS: MacOS
 - Version: 11.4

**Comment by hdevalke** [comment]
Indeed, if no range is given it takes the range `..{commit-ish}`.
To check a single commit you could make a range from it `convco check {commit-ish}^..{commit-ish}`.

This is the expected coded behaviour, see: https://github.com/convco/convco/blob/master/src/cmd/check.rs#L29

It is true however, that this is not documented.

**Comment by hdevalke** [comment]
I could add a `--no-traversal` or `--no-walk` flag to change the behaviour in case a sinlge commit is given

**Comment by BroderickCarlin** [comment]
Any specific reason for masquerading the single provided commit-ish as `..{commit-ish}`? Just from the perspective of someone coming upon the tool it seems that doing the opposite would be more intuitive. For example, if a single commit-ish is provided it checks that commit and only that commit. If `--traversal` or `--walk` is provided it instead does the range `..{commit-ish}`

**Comment by hdevalke** [comment]
I added a max number option to limit the number of commits to check. 
This is similar to the behaviour of `git log`.
