### ISSUE TITLE
Arrow keys not supported for moving cursor in dialoguer input

### ISSUE THREAD

**Issue by beeb** [convco/convco#197]
**Describe the bug**
In the `commit` command, when writing text in any of the text inputs, navigation with arrow keys is not supported (escape sequences are printed instead).

**To Reproduce**
1. `convco commit`
2. choose type (enter)
3. In "scope", write "foo" and then the left arrow key
4. Result: `foo^[[D`

**Expected behavior**
The cursor is moved left

**System (please complete the following information):**
 - OS: Ubuntu
 - Version: 23.10

**Additional context**

This crate should use [`interact_text`](https://docs.rs/dialoguer/0.11.0/dialoguer/struct.Input.html#method.interact_text) instead of `interact` for dialoguer inputs

**Comment by hdevalke** [comment]
Thank you for pointing to the solution

**Comment by beeb** [comment]
Thanks for the quick fix!
