### ISSUE TITLE
Breaking change is missing spaces in description

### ISSUE THREAD

**Issue by ctron** [convco/convco#221]
**Describe the bug**

In the case of a "breaking change", the description is missing a space between the line breaks:

```
### ⚠ BREAKING CHANGE

* Titles, footers, actions, and selectable actions all can't behandled by the Card object directly anymore and need to be delegated to the
more specific classes.

### ⚠ BREAKING-CHANGE

* Those type aliases helped with the migrate. From nowone please use the new type names.
* The legacy version of the Select component isdeprecated in PF5. You need to upgrade to the newer components.

```

Note the `behandled`,  `nowone`, and `isdeprecated` (which is the line break in the commit).

**To Reproduce**
1. Clone 'https://github.com/patternfly-yew/patternfly-yew'
2. Run `convco ...`
3. See error ...

**Expected behavior**

When lines are concatenated, there should be a space.

**System (please complete the following information):**
 - OS: fedora, ubuntu,
 - Version: 39, 22.04

**Additional context**

**Comment by hdevalke** [comment]
It was not the goal to concatenate the multi line footers. see #223
