### ISSUE TITLE
override commit description required length

### ISSUE THREAD

**Issue by sripwoud** [convco/convco#227]
Is [requiring a commit description longer than 10 chars](https://github.com/convco/convco/blob/7b60f34e6df6a932adf5628cd6054e1c1f564e17/src/cmd/commit.rs#L97) part of the conventional commits spec?

I don't see a corresponding option in `convco config --default`.  
Could we have a way to configure/override this?

Otherwise a message like `chore: format`, which is a valid "conventional commit" as per the specs, is rejected by `convco`

**Comment by hdevalke** [comment]
Conventional commits specs do not say anything about the minimum or maximum length, so it is up to the tool to set some limits. But it is indeed better if this would be configurable.

**Comment by hdevalke** [comment]
@sripwoud I made #228 to add this as a configuration option. Would this fit for you or should this also be available as a cli option?

**Comment by sripwoud** [comment]
@hdevalke a config option like you implemented is perfect for me!
