### ISSUE TITLE
Git bare repository support

### ISSUE THREAD

**Issue by kamack38** [convco/convco#230]
**Is your feature request related to a problem? Please describe.**
Currently, git bare repositories aren't supported.

**Describe the solution you'd like**
Add support for `--git-dir` and `--work-tree` flags to the CLI, and maybe change `-C` to `-W` and add `-D` short flag.

**Describe alternatives you've considered**
Running with `-C` with the git-dir as an argument

**Additional context**
To use a git bare repository, one has to supply `--git-dir` and `--work-tree` flag to git.

I'm coming from `git-cz` and it has a great feature of working with `git` command as its subcommand (because its binary is named `git-*` and all binaries called like that, function as git subcommands) and because of this it can read this flags directly from git, so that would also be great to have, but perhaps it's out of scope for this issue.

**Comment by hdevalke** [comment]
The difference with git-cz and convco is that convo uses libgit2 instead of depending on the git binary available.
Bare repos do work (at least with v0.5.1. Otherwise I need a reproducible script.

`-C` has been taken to change the work dir as does the git command. adding `--git-dir` and `--work-tree` would need extra development. although `GIT_DIR` and `GIT_WORK_TREE` variables should probably support your use case.

**Comment by kamack38** [comment]
Here's an example:
```
❯ git init --bare git-dir
Initialized empty Git repository in /home/kamack38/Downloads/test/git-dir/
❯ touch smth
❯ git --git-dir=git-dir --work-tree=./ add smth
❯ convco commit
could not find repository at '.'; class=Repository (6); code=NotFound (-3)
could not find repository at '.'; class=Repository (6); code=NotFound (-3)
❯ cd git-dir/
❯ convco commit
✔ type · feat
✔ scope · fsd
✔ description · dfsdfadfasdfa
✔ optional BREAKING change · 
✔ issues (e.g. #2, #8) · 
fatal: this operation must be run in a work tree
git commit failed: exit status: 128

**Comment by kamack38** [comment]
But yeah it works when setting the `GIT_DIR` and the `GIT_WORK_TREE` flags.

**Comment by hdevalke** [comment]
I see for convco commit it does shell out instead of using libgit2.
You can use `git -c core.editor="convco commit" commit'` or define an alias: `git config --global alias.convco-commit '-c core.editor="convco commit" commit'` and use `git convco-commit`

**Comment by kamack38** [comment]
Thank you! This alias works perfectly.
