### ISSUE TITLE
Add support to bump version from user provided current value

### ISSUE THREAD

**Issue by whichwit** [convco/convco#245]
**Is your feature request related to a problem? Please describe.**
Currently `convco version` works off of git tags only. It is difficult to use `convco` in solutions with versions tracked in files or multiple versions.

**Describe the solution you'd like**
Add support to allow and utilize user provided current version, either from stdin or command line parameters.

**Describe alternatives you've considered**
Keeping all projects under the same version, tracked via git tag.

**Additional context**
Trying to maintain a Java monorepo setup with projects tracked in Maven's pom.xml file. All projects have different versions.

**Comment by hdevalke** [comment]
You can use the `--prefix <PREFIX> --paths <PATH>` to differentiate between different projects in the mono repo.
So for example if you have a repo with `/project1` and `/project2` and you want to tag them `project1-vx.y.z` and `project2-va.b.c` you can use `convco version --bump -p project1-v -P project1` and `convco version --bump -p project2-v -P project2` to calculate the next version.

**Comment by whichwit** [comment]
Thanks, the `--paths` can be used for multiple projects within a monorepo. This request is more about using external version values. 

For example, say there are multiple Java modules within a Maven monorepo, each with their own version numbers. Can `convco` determine the current version numbers from the `pom.xml` files for any module?

**Comment by hdevalke** [comment]
Convco can't as it is not aware of the pom.xml file. But i would expect the maven modules to be organized in 

```
- pom.xml (parent)
 | - module1/pom.xml
 | - module2/pom.xml
```

so to use convco with this multimodule maven you could use the same solution as shown in https://github.com/convco/convco/issues/245#issuecomment-2294796932. 

If you can't tag each submodule with a different prefix, you could use `convco version --bump --label -P module1` and then use a shell script or a maven plugin to bump to a new minor/major/patch version.
