### ISSUE TITLE
Fast forward merge management

### ISSUE THREAD

**Issue by taorepoara** [convco/convco#249]
**Describe the bug**
When doing fast forward merges (with GitLab for example), convco seems to not get the right release.

I merged commits on my beta (tagged `1.0.0-beta.1`) branch to my main (tagged `1.0.0`) and when I use `convco version` it displays the beta version (`1.0.0-beta.1`), instead of the main one (`1.0.0`).

Also when I use the `--bump` flag, it gives the same main version (`1.0.0`).

Results:
- `convco version`: `1.0.0-beta.1`
- `convco version --bump`: `1.0.0-beta.2`

**To Reproduce**

- Create a git tag with a prerelease version from a commit.
- Create a git tag with a release version from the same commit.
- Add a feature or fix commit after the previous one.
- Try to use convco.

**Expected behavior**

The expected results are:
- `convco version`: `1.0.0`
- `convco version --bump`: `1.1.0`

**System (please complete the following information):**
 - OS: Debian
 - Version: 12

**Additional context**
Those tags where made with semantic release. It was a test before moving to convco.

**Comment by hdevalke** [comment]
Thank you for reporting. I could reproduce the issue. I will try to fix this soon.

**Comment by hdevalke** [comment]
Just to be sure i did understand the issue correctly you have a prerelease tag on the same commit, it does print out the prerelease version instead of the release version 

```
❯ git tag v0.1.0 94e736239e2841f3f829d1c68816ef610fc7e1e8
❯ git tag v0.1.0-beta 94e736239e2841f3f829d1c68816ef610fc7e1e8
❯ convco version
0.1.0-beta
```

**Comment by taorepoara** [comment]
Yes, exactly.

IMO, convco version should display the highest version corresponding to this commit.

We could have the same problem between a beta tag and a rc tag.
The rc tag should be prioritized:
- is there a corresponding release: display the release 
- is there pre releases: display the last pre release sorting by alphabetical order of there pre release channel

I would great to display the pre release tag when using the `--prerelease` option.

With your previous test, the expected result would be :
- `convco version` : 0.1.0
- `convco version --prerelease beta`: 0.1.0-beta

Let me know if you need more examples.

**Comment by tobikris** [comment]
Is this fixing your issue? https://github.com/convco/convco/pull/250

**Comment by taorepoara** [comment]
I'll test it tomorrow on one of our project

**Comment by taorepoara** [comment]
Hi,
I actually can't test it before it's released on this project this I'm working in a bank with a closed dev environment. I use the Docker image to use convco (and our Docker env is pretty closed two), sorry.

**Comment by hdevalke** [comment]
It has been released. Can you confirm it resolved your issue?

**Comment by taorepoara** [comment]
Yes, it seems to work fine, thanks !

I'll try it on other project and start replacing Semantic Release by it.

I'll open new issues if I find new problems.

**Comment by taorepoara** [comment]
This work perfectly. I created another issue linked to our workflow, but not for the same problem: https://github.com/convco/convco/issues/264
