### ISSUE TITLE
Malformed Commit Message

### ISSUE THREAD

**Issue by da-moon** [convco/convco#25]
**Describe the bug**

`convco commit` generates a commit message that has an exclamation mark (`!`) after scope in case there are any whitespaces in `optional BREAKING change` step.

**To Reproduce**

1. run `convco commit`
2. put in empty spaces when asked for input in `optional BREAKING change` stage

output is in the form of

```console
<type>(<scope>)!: <message>
```

**Expected behavior**

- commit header should be in form of `<type>(<scope>): <message>`

**System (please complete the following information):**
 - OS: ArchLinux

**Comment by hdevalke** [comment]
Closed by #26
