### ISSUE TITLE
Consider using conventional_commit_parser crate 

### ISSUE THREAD

**Issue by oknozor** [convco/convco#27]
Hello, 

I am maintaining [cocogitto](https://github.com/oknozor/cocogitto/) which looks a lot like convco. I just released the first version of a [parser crate for the conventional commit specification](https://crates.io/crates/conventional_commit_parser) for my own and I was thinking you might be interested. It might make it easier to stick to the spec for both of us. 

If you are interested I would gladly add you as a maintainer on the repo, we could even ask the conventional commit organization to host it. 

Let me know what you think.

**Comment by hdevalke** [comment]
Nice tool ccogitto.
Thank you for reaching out, but I am short in time, and don't see much added value of using the same parser now.

Did you see any divergences between convco and cocogitto parser?
