### ISSUE TITLE
version bump prerelease: do not increment if a tag exists for the current commit

### ISSUE THREAD

**Issue by taorepoara** [convco/convco#284]
**Is your feature request related to a problem? Please describe.**

When using `convco version --bump --prerelease beta` the result always increment the version heaven if there is already a corresponding tag for the current commit.

**Describe the solution you'd like**

IMO it would be better to return the (first/last) tag corresponding to the commit for the same prerelease channel to have a behavior close to the main release release workflow.

**Describe alternatives you've considered**

...

**Additional context**

To reproduce:

- call `convco version --bump --prerelease beta`
- create a git tag with the given version number
- call `convco version --bump --prerelease beta` again

The version is incremented heaven if there where no change between the two calls.

**Comment by hdevalke** [comment]
I understand the issue, but wonder if it should return the same version or an error.

**Comment by taorepoara** [comment]
> I understand the issue, but wonder if it should return the same version or an error.

It should return the same version since the same command without the `--prerelease` option does not return error but the last tagged version.

IMO it would be better to return an error but in both cases. The behavior for prereleases should be the same as for releases.

**Comment by hdevalke** [comment]
The command [here](https://github.com/convco/convco/blob/main/src/cli.rs#L65) says `--prerelease` requires `--bump` but it is not enforced

**Comment by taorepoara** [comment]
> The command [here](https://github.com/convco/convco/blob/main/src/cli.rs#L65) says `--prerelease` requires `--bump` but it is not enforced

I don't understand your comment 😅

What I meant is that failing should linked to the `--bump` flag, not to the `--prerelease` option only.

**Comment by hdevalke** [comment]
sorry indeed, it is enforced to use bump. I was reading the issue and pr #285 on my phone.
The behaviour now for `convco version --bump` does indeed just return the current version if nothing changed (same commit or no fix/feat commit).

for pre releases this should be indeed the same behavior.
