### ISSUE TITLE
Allow limiting the history

### ISSUE THREAD

**Issue by ctron** [convco/convco#35]
**Is your feature request related to a problem? Please describe.**

I want to automatically create the changelog for a github release. As information, I do have the current tag only.

**Describe the solution you'd like**

I would like to have a way to limit the generation up until (excluding) the previous tag.

So assuming I am running as the release, and have the current release in `$TAG`. I would like to run e.g:

    convco changelog ..$TAG --max-tags 1

Which would limit the output to one tag, starting with the tag provided.

**Describe alternatives you've considered**

* Actually query the GitHub releases API: that might be more correct than just checking for the "previous" tag, but also more complicated and limited
* Additionally there could be an "ignore refs" pattern, which could allow ignoring tags in the process of counting tags.

**Additional context**

None

**Comment by hdevalke** [comment]
Thanks for the suggestion. For checking we have a `--max-count`, but it counts the commits, not the tags.
For the changelog it could indeed be good to limit the number of versions, but probably it should be `--max-majors` `--max-minors` `--max-versions`.

For now if you would limit on a tag boundary you could use:

```sh
convco changelog $(git tag --sort v:refname -l 'v*' | tail -n5 | head -n1)..$TAG
```

which would create the changelog for $TAG and 3 other versions.

Ignoring a version is more complicated, e.g if you would ignore v2.0.1 should those changes be visible under v2.0.2 or not at all?

**Comment by ctron** [comment]
I like the proposal, and thanks for the alternative to try out.

> Ignoring a version is more complicated, e.g if you would ignore v2.0.1 should those changes be visible under v2.0.2 or not at all?

A good question. I was simply assuming it would indeed end up under the 2.0.2 in this case. The case I had in mind was, when the some other mechanism (like helm charts) create tags on the repository as well. Those would have a different format though. So you could say `v.*` is included in counting, all others are not (like `charts-2.0.2`). So it would not stop, but add more commits to the processing. Until it reaches e.g. `v2.0.1`.

**Comment by hdevalke** [comment]
convco is only walking between tags with the prefix (`v` by default). 
so the other tags are ignored. I'll try to add a `--max-versions` flag this week as that would be closest to your initial request. the other flags can be added later

**Comment by hdevalke** [comment]
Would you mind testing the branch [`max-versions`](https://github.com/convco/convco/tree/max-versions)?

**Comment by ctron** [comment]
> Would you mind testing the branch [`max-versions`](https://github.com/convco/convco/tree/max-versions)?

Works like a charm!

**Comment by hdevalke** [comment]
I'll close this issue for now.
To hide a version, i think it is better just to untag it.

for the max-majors, max-minors, I think it is better to add a flag to `convco version` to select `major -<n>` or `minor -<n>` where it would print out that version. This way it could be used to create the lower limit `convco changelog "$(convco version --major -1)..".
A [version req](https://docs.rs/semver/latest/semver/struct.VersionReq.html) filter could be added to `changelog`.
