### ISSUE TITLE
Pass commit message with `convco commit -m`

### ISSUE THREAD

**Issue by hoodie** [convco/convco#36]
Hi there,
lovely tool, I use it a lot. There is one thing I always assume it does, but doesn't.
You can already pass `--message` or `-m` to `git commit` and it will fill in the message instead of opening the editor.

Do you think this would be complicated to add?

**Comment by hdevalke** [comment]
It is not too complicated to add, but I think we need two flags, one for the description (`--descripton, -d`) and one for the body (`--body, -b`) and maybe also a (`--footer, -f`) where body and footer could occur more than once.

**Comment by hoodie** [comment]
The way the git command line handles it is that you can pass multiple `-m` flags and it will just add an empty line between each of these lines.

If we implemented it like that then it would be both simple and compatible with git. Why would you want to be able to pass the footer before the description?
Just saying

**Comment by hdevalke** [comment]
A conventional commit message has the following format:

```plain
<type>[optional scope]: <description>

[optional body]

[optional footer(s)]
```

Where would `-m` fit? For now there are flags for the type but none for the scope, description, body and footers.
One option is to make a flag for each. Another option is for to use the first `-m` as description, the others as body.

if no `-m` is given, the editor could open. if `-m` is given no editor opens, unless `--edit` is given. 

Before implementing this feature, I need to know better how it will be used.

**Comment by hoodie** [comment]
Yes, this sounds basically how I would expect it to behave.
For this commit message

```
feat: this is cool stuff

but actually, not
```
I'd probably like to type the following:
`$ convco commit --feat -m "this is cool stuff" -m "but actually, not"`

I'm not sure about scope, I could imagine actually making it an optional parameter to `--feat`, because then your command input would almost ready like the commit message itself

`$convco commit --feat convco -m "new commit cli" -m "you can now pass the scope to the <type> flag"`

would be 

```
feat(convco): new commit cli

you can now pass the scope to the <type> flag
```

what do you think?

**Comment by hdevalke** [comment]
For scope and footers I think we should add a separate flag.
I also think that if the minimal mandatory options are provided the interactive mode should be disabled unless `-i,--interactive` is provided. `convco commit --feat -m 'some description'` would then be the minimal command to provide to not go in interactive mode.

I hope to find some time to implement this soon.

**Comment by hdevalke** [comment]
I am working on this new feature.
Would you like to test https://github.com/convco/convco/tree/feat-36 ?

if either `-i` or no type or description is given, the wizard will show. Else it will commit, if the message is conform the conventional commit spec.

**Comment by hoodie** [comment]
looks pretty great!

I just tried out the `--footer` flag (I hadn't known that something like `BREAKING CHANGE` is a footer
but maybe there should a space after the `:` that is emitted?

**Comment by hdevalke** [comment]
Thanks for checking. I'll probably make a new release before the end of the year
