### ISSUE TITLE
`BREAKING CHANGE:` footer doesn't cause major version bump

### ISSUE THREAD

**Issue by matthias-stemmler** [convco/convco#40]
**Describe the bug**
When there is a commit with a `BREAKING CHANGE:` footer but no `!` after the type/scope, this doesn't cause a major version bump (or minor in the case of a `0.x.y` version). However, according to point 11 of the [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/#specification), it should because a breaking change can be indicated **either** by a `!` **or** a `BREAKING CHANGE:` footer.

**To Reproduce**
Steps to reproduce the behavior: Run
```
git init
git commit --allow-empty -m "chore: initial"
git tag v1.0.0
git commit --allow-empty -F- <<EOF
feat: feature with breaking change

BREAKING CHANGE: some breaking change
EOF
convco version --bump
```
This outputs `1.1.0`. When you change `feat:` into `feat!:`, it (correctly) outputs `2.0.0`.

**Expected behavior**
It should output `2.0.0` even without the `!` as a `BREAKING CHANGE:` footer already declares a breaking change on its own.

**System:**
 - OS: ubuntu
 - Version: 20.04

**Comment by hdevalke** [comment]
Thanks for reporting.
This is either a problem in parsing the commit message or in the logic here: https://github.com/convco/convco/blob/master/src/cmd/version.rs#L76-L105

**Comment by matthias-stemmler** [comment]
Thanks for the quick reply and the fix. 
And thanks for creating this great tool!
