### ISSUE TITLE
Configuration for major version zero bump

### ISSUE THREAD

**Issue by gotson** [convco/convco#45]
**Is your feature request related to a problem? Please describe.**
I see in the doc:

> Major version zero (0.y.z) has the following rules:
> 
> A commit of type fix will increase the PATCH version.
> A commit of type feat will increase the PATCH version.
> A commit with a breaking change increases the MINOR version.

This is the first time i see this among all the tools that handle conventional commits.

I would like to use the normal bumping behavior, even for version zero.

**Describe the solution you'd like**
A configuration key to use the normal bumping behavior even for major version zero.

**Describe alternatives you've considered**
Using another tool, but this one looks simple and nice!

**Comment by gotson** [comment]
I see in the documentation that there is a `preMajor` configuration key, but it also says that it's set by convco automatically. I tried changing it in my `.versionrc`, but that doesn't change the behaviour.

**Comment by hdevalke** [comment]
`preMajor` is always calculated by the tool.

semver says:

> 4.  Major version zero (0.y.z) is for initial development. Anything MAY change at any time. The public API SHOULD NOT be considered stable.

and in the faq:

> How should I deal with revisions in the 0.y.z initial development phase?
>
> The simplest thing to do is start your initial development release at 0.1.0 and then increment the minor version for each subsequent release.

Rusts cargo defines

> This guide uses the terms "major" and "minor" assuming this relates to a "1.0.0" release or later. Initial development releases starting with "0.y.z" can treat changes in "y" as a major release, and "z" as a minor release. "0.0.z" releases are always major changes. This is because Cargo uses the convention that only changes in the left-most non-zero component are considered incompatible.

You say:

> I would like to use the normal bumping behavior, even for version zero.

You can do  `convco version --major` when your code is ready to release v1.0.0.

> How do I know when to release 1.0.0?
>
> If your software is being used in production, it should probably already be 1.0.0. If you have a stable API on which users have come to depend, you should be 1.0.0. If you’re worrying a lot about backwards compatibility, you should probably already be 1.0.0.

Do you have examples of tools that always increase major for breaking changes in pre-major releases?

**Comment by gotson** [comment]
> `preMajor` is always calculated by the tool.

i guess i was surprised to see an entry for it in the configuration help, while it cannot be configured.

---

I was actually not much bothered by the breaking change increasing minor, but more by features increasing patch. I use `semantic-release` now, which behaves in the same way for both major zero and other version, but after checking their website, they don't support major zero at all, which explains why the tool doesn't have a different behaviour.

After re-reading SemVer specs, i do agree with you, even though it was unintuitive at first for me.
