### ISSUE TITLE
Parser doesn't parse multiple reference on the same line

### ISSUE THREAD

**Issue by gotson** [convco/convco#48]
**Describe the bug**
When parsing a commit like so:

```
fix: correct minor typos in code

closes #1, closes #2
```

the resulting `Commit` should have 2 `Footer`: `[Footer { key: "closes", value: "1" }, Footer { key: "closes", value: "2" }] }`

With the current code it has a single `Footer`: `[Footer { key: "closes", value: "1, closes #2" }] }`

Another accepted form is also `closes #1, #2`, which should also work.

**Additional context**
- Other tools like `semantic-release` can parse those properly.
- example at the bottom of https://www.conventionalcommits.org/en/v1.0.0/ : 
```
revert: let us never again speak of the noodle incident

Refs: 676104e, a215868
```

**Comment by hdevalke** [comment]
For the second example, the parser indeed parses this to: `[Footer { key: "Refs", value: "676104e, a215868" }] }`

The struct for the footer is 

```rust
pub(crate) struct Footer {
    pub(crate) key: String,
    pub(crate) value: String,
}
```

The footers are stored in a `Vec` so multiple footers with the same key should not be a problem.
The value however should change to a `Vec<String>`.

For the first example, you are right, a footer does not need to be on its own line.
However, it does not say anything about comma separated footers, nor values.
I will have a look how the [reference parser](https://github.com/conventional-commits/parser) handles this.

> One or more footers MAY be provided one blank line after the body. Each footer MUST consist of a word token, followed by either a :<space> or <space># separator, followed by a string value (this is inspired by the git trailer convention).
> A footer’s token MUST use - in place of whitespace characters, e.g., Acked-by (this helps differentiate the footer section from a multi-paragraph body). An exception is made for BREAKING CHANGE, which MAY also be used as a token.
> A footer’s value MAY contain spaces and newlines, and parsing MUST terminate when the next valid footer token/separator pair is observed.

**Comment by hdevalke** [comment]
Results with the reference parser show that a footer should start on a new line to recognize all issue references. 

```sh
❯ ./scripts/inspect.js cc "fix: correct minor typos in code

closes #1, closes #2"
-----
{
  "body": "",
  "subject": "correct minor typos in code",
  "type": "fix",
  "scope": null,
  "notes": [],
  "references": [],
  "mentions": [],
  "merge": null,
  "revert": null,
  "header": "fix: correct minor typos in code",
  "footer": null
}

❯ ./scripts/inspect.js cc "fix: correct minor typos in code

closes #1 closes #2"
-----
{
  "body": "",
  "subject": "correct minor typos in code",
  "type": "fix",
  "scope": null,
  "notes": [],
  "references": [],
  "mentions": [],
  "merge": null,
  "revert": null,
  "header": "fix: correct minor typos in code",
  "footer": null
}

❯ ./scripts/inspect.js cc "fix: correct minor typos in code

closes #1, #2"
-----
{
  "body": "",
  "subject": "correct minor typos in code",
  "type": "fix",
  "scope": null,
  "notes": [],
  "references": [],
  "mentions": [],
  "merge": null,
  "revert": null,
  "header": "fix: correct minor typos in code",
  "footer": null
}

❯ ./scripts/inspect.js cc "fix: correct minor typos in code

closes #1,#2"
-----
{
  "body": "",
  "subject": "correct minor typos in code",
  "type": "fix",
  "scope": null,
  "notes": [],
  "references": [],
  "mentions": [],
  "merge": null,
  "revert": null,
  "header": "fix: correct minor typos in code",
  "footer": null
}

❯ ./scripts/inspect.js cc "fix: correct minor typos in code

closes #1 #2"
-----
{
  "body": "",
  "subject": "correct minor typos in code",
  "type": "fix",
  "scope": null,
  "notes": [],
  "references": [],
  "mentions": [],
  "merge": null,
  "revert": null,
  "header": "fix: correct minor typos in code",
  "footer": null
}

❯ ./scripts/inspect.js cc "fix: correct minor typos in code

closes #1
closes #2"
-----
{
  "body": "",
  "subject": "correct minor typos in code",
  "type": "fix",
  "scope": null,
  "notes": [],
  "references": [
    {
      "prefix": "#",
      "action": "closes",
      "issue": "1"
    },
    {
      "prefix": "#",
      "action": "closes",
      "issue": "2"
    }
  ],
  "mentions": [],
  "merge": null,
  "revert": null,
  "header": "fix: correct minor typos in code",
  "footer": null
}
```

**Comment by gotson** [comment]
The reference implementation contradicts the example on their spec:

```
revert: let us never again speak of the noodle incident

Refs: 676104e, a215868
```

**Comment by gotson** [comment]
> The struct for the footer is
> 
> ```rust
> pub(crate) struct Footer {
>     pub(crate) key: String,
>     pub(crate) value: String,
> }
> ```
> 
> The footers are stored in a `Vec` so multiple footers with the same key should not be a problem. The value however should change to a `Vec<String>`.

I would instead unwrap the values, and render it as 2 `Footer` with each the same key and a different value. But that's just my opinion.

**Comment by hdevalke** [comment]
I went through the code of conventional changelog and saw they parse references line per line.
So I would say references are not part of the specification, but an addition used by conventional changelog.

If we change the [`struct Commit`](https://github.com/convco/convco/blob/master/src/conventional/commits.rs#L73) to hold a list of references we can change the logic in the `parse` function. References are now only parsed when transforming the Commit to be used in the handlebar template.

```rust
pub struct Commit {
    pub(crate) r#type: Type,
    pub(crate) scope: Option<String>,
    pub(crate) breaking: bool,
    pub(crate) description: String,
    pub(crate) body: Option<String>,
    pub(crate) footers: Vec<Footer>,
    pub(crate) references: Vec<Reference>,
}
```

**Comment by hdevalke** [comment]
As you can see the branch [fix-parse-issues](https://github.com/convco/convco/compare/fix-parse-issues) is able to parse multiple references.
However, the example below will never parse correctly as these are not issues, but commit shas.

```
revert: let us never again speak of the noodle incident

Refs: 676104e, a215868
```
