### ISSUE TITLE
`convco version` output for unreleased project

### ISSUE THREAD

**Issue by gotson** [convco/convco#49]
**Is your feature request related to a problem? Please describe.**
I would like to use convco to detect whether a change worthy of a release happened. The idea would be to compare the value of `convco version` and `convco version --bump`, if it is different, then a release should happen.

For an unreleased repo with no semver tags, the output of `convco version` is always `0.1.0`, whatever the options passed.

This prevents me from having logic that can be applied all the time, as i need to have special handling for the initial release.

**Describe the solution you'd like**
I think for an unreleased project, the following commands should output the following results:
- `convco version` : `unreleased`
- `convco version --bump` : `0.1.0` (assuming existing behaviour to start at that version)
- `convco version --major` : `1.0.0`
- `convco version --minor` : `0.1.0`
- `convco version --patch` : `0.0.1`

**Describe alternatives you've considered**
Special handling for initial release by checking the tags from git directly.

**Comment by hdevalke** [comment]
Indeed, on a repo with no tags, the version is not always set logically:

```
❯ git commit --allow-empty -m 'fix: abc'

❯ convco version --bump
0.1.0

❯ convco version 
0.1.0

❯ convco version --minor
0.1.0

❯ convco version --major
0.1.0

❯ convco version --patch
0.1.0
```

This logic should be added in this [`else` block](https://github.com/convco/convco/blob/master/src/cmd/version.rs#L143).

**Comment by hdevalke** [comment]
@gotson I implemented it as you'd like except for the version of the unreleased one I choosed to print `0.0.0` instead of `unreleased`
