### ISSUE TITLE
check should fail on unrecognized types

### ISSUE THREAD

**Issue by Kissaki** [convco/convco#53]
convco check parses the commit information in `CommitParser`, which verifies the correct message format.

However, the parsed type is never verified to be one of the configured types in Config.

**Comment by hdevalke** [comment]
For this repo, this is the output:

```
❯ cargo run -- check
   Compiling convco v0.3.10 (/home/hannes/code/convco)
    Finished dev [unoptimized + debuginfo] target(s) in 3.75s
     Running `target/debug/convco check`
FAIL  38be02d  wrong type: doc  doc: clarify cmake is needed to build
FAIL  8c4dbb6  wrong type: doc  doc: improve gitlab section in `README.m...
FAIL  ffcf34a  scope does not match regex: changelog|check|commit|version  ci(docker): Add a dockerfile
FAIL  724bb2b  first line doesn't match `<type>[optional scope]: <description>`  release v0.3.0
FAIL  155e652  scope does not match regex: changelog|check|commit|version  build(deps): bump versions

5/121 failed
```

38be02d and 8c4dbb6 are newly detected

**Comment by ite-klass** [comment]
Are you saying it’s working/supposed to work like that already?

**Comment by hdevalke** [comment]
> Are you saying it’s working/supposed to work like that already?

No, that is the output of #55. Before merging it I would like to know if that's what you expected and if the error message is fine.

**Comment by Kissaki** [comment]
Assuming the exit code is non-0, yes, that seems reasonable.

**Comment by Kissaki** [comment]
Thank you! :)

**Comment by prewk** [comment]
Is this still the case?

Shouldn't `echo "whatever: Test" | convco check --from-stdin` give me an error when using the [default configuration](https://convco.github.io/configuration/) because `whatever` isn't a type?

**Comment by hdevalke** [comment]
The code is indeed only parsing the message, but not checking the types when read from stdin.

**Comment by jbergstroem** [comment]
> Shouldn't echo "whatever: Test" | convco check --from-stdin give me an error when using the [default configuration](https://convco.github.io/configuration/) because whatever isn't a type?

I assumed this would work without a git repository as well:
```console
$ echo "whatever: Test" | convco check --from-stdin
Error: could not find repository from '.'; class=Repository (6); code=NotFound (-3)
```
