### ISSUE TITLE
template for commit message

### ISSUE THREAD

**Issue by Kissaki** [convco/convco#54]
The commit message form created by `convco commit` should be configurable.

Specifically, we intend to put ticket references into the summary line rather than into a footer field.

**Comment by hdevalke** [comment]
Can you explain more how this configuration should look like?

**Comment by Kissaki** [comment]
Given that Handlebars is being used for the changelog template, I would assume it would be a handlebars template too.

Values would be type, scope, summary, description, ticket-ids - and whatever makes sense/is tracked (breaking change?).

pseudo code:

```
{type}{scope}: {summary}

{description}

{#if ticket-ids}Refs: {#each ticket-ids}({string.join ", " .}){#end}{#end}
```

```
{type}{scope}: {summary} {#each ticket-ids}({string.join "," .}){#end}

{description}
```

**Comment by hdevalke** [comment]
Here you can see the default template: https://github.com/convco/convco/pull/71/files#diff-aa0e81d646a5254c9cf39a982a9f499e745293329dda29227ef3761df8a0e1e5

You can probably adapt it to fit your needs. I guess you want something like:

```hbs
{{type}}{{#if scope}}({{scope}}){{/if}}{{#if breaking}}!{{/if}}: {{description}}{{#if issues}}({{#each issues}}{{this}}{{#unless @last}}, {{/unless}}{{/each}}){{/if}}
{{body}}
{{#if breaking_change}}BREAKING CHANGE: {{breaking_change}}{{/if}}

{{#each footers}}
{{this}}
{{/each}}
```
