### ISSUE TITLE
changelog parameter to include hidden sections

### ISSUE THREAD

**Issue by ite-klass** [convco/convco#56]
We intend to use convco changelog to generate a changelog for a new version / upcoming changes.

The primary intention is to use the generated changelog as the basis for user-facing release notes. We have hidden development-centric sections in the configuration.

However, it could be useful to generate a changelog with these hidden sections too, as insight and a listing for developers.

An additional parameter like `--include-hidden-sections` on `changelog` could allow generating a changelog of all sections instead of only the configured non-hidden sections.

Overall it would be a parameter useful outside of the primary, configured, and possibly continuous changelog generating workflow.

**Comment by hdevalke** [comment]
Would you mind to try https://github.com/convco/convco/pull/58?

As the default section for all types but feat and fix is Other, you will probably want to play with the config.
You can find the default config [here](https://convco.github.io/configuration/#default-configuration).

**Comment by ite-klass** [comment]
Looks good to me!
