### ISSUE TITLE
Prefix not working

### ISSUE THREAD

**Issue by MAHDTech** [convco/convco#57]
Not sure If I have misuderstood, but the "--prefix" flag doesn't seem to be operating as I would expect.

**Describe the bug**

The prefix is not added to the displayed version.

**To Reproduce**

- Install comvco v0.3.10 (2022-04-24)
- run `convco version --prefix "HELLO-" `
- run `convco version --prefix "HELLO-" --bump`

**Expected behavior**

Current version should be

`HELLO-0.0.0`

Next version should be

`HELLO-0.0.1`

**System (please complete the following information):**

 - OS: Debian
 - Version: Bullseye

I'm also having the same issue in GitLab CI and was able to reproduce locally.

**Additional context**

Here is an example git commit history of a repo I'm using

```bash
Author: Git Bot <Git-Bot@domain.com>
Date:   Fri Jun 24 04:43:59 2022 +0000

    fix: Fixed a bug in the widget collector

commit a1d032cb7485a535254f180f5488484110be1623
Author: Git Bot <Git-Bot@domain.com>
Date:   Fri Jun 24 01:40:55 2022 +0000

    fix(api)!: Fixed a bug

commit 49ee67ce3f9b1d8403e15b8fca9fa7b0db6923e5
Author: Git Bot <Git-Bot@domain.com>
Date:   Fri Jun 24 01:30:48 2022 +0000

    chore: did a thing

commit ed3a69fa066d33a3314116e081e7c517e1c4bc3e
Author: Git Bot <Git-Bot@domain.com>
Date:   Fri Jun 24 01:10:51 2022 +0000

    feat: Initial release
```

**Comment by hdevalke** [comment]
The prefix is only used to find the git tags containing the semantic version. A prefix is not part of the semantic version. Maybe a new flag `--print-prefix` could be added.

**Comment by MAHDTech** [comment]
Thanks for the explanation, makes sense now.
