### ISSUE TITLE
Generated changelog does not include merge commits

### ISSUE THREAD

**Issue by ite-klass** [convco/convco#61]
The generated changelog does not include merge commits.

In our workflow we often have multiple commits in a work branch. We then put them up for review in a merge request.
The merge request receives a title which includes a ticket reference, and description.

After review, commits as they make sense are merged into the target branch with a merge commit.
The MR title and description become the merge commits message (summary/title with ticket reference and description).

A generated changelog in this workflow should include the merge commit messages, but not the merged commits.

At the moment, convco generates a changelog only from individual commits including merged commits, but excluding merge commits.

I would consider merge commits missing a bug, and I guess being able to include merge commits while excluding merged commits would be a feature request.

**Comment by hdevalke** [comment]
Merge commits are filtered out on purpose here: https://github.com/convco/convco/blob/master/src/cmd/changelog.rs#L152 

Are the merge commit messages following the conventional commits standard?

**Comment by ite-klass** [comment]
Yes they do.

**Comment by ite-klass** [comment]
Wouldn’t conventional commits generally apply to merge commits too though?

It is a convention for commits. Why would one exclude merge commits from it? The convention does not mention any such thing at all.

I understand you may not want to break backwards compatibility. But I think that should be made explicit, and I would go for a warn and breaking change over a few releases.

**Comment by ite-klass** [comment]
> When using merge commits each parent of the merge commit should follow the convention, so ignoring merge commits is not an issue

I don’t see what you mean? A merge commit is a commit too.

Are you saying the changelog should list the individual changes rather than the summarizing/conclusive change?

If a merge commit is `feat` for introducing a new feature, which merges individual commits of different types (prep + impl) and scopes (components/concerns), it makes natural sense to me to only include the conclusive merge commit reference into the changelog.

For me, a merge commit is intuitively and naturally a change description that replaces the individual change descriptions.

**Comment by ite-klass** [comment]
As for the linked comment, that’s an opinionated comment I disagree with. Using merges as a second level structuring tool to group changes is useful.

**Comment by hdevalke** [comment]
Weather using merge commits or not for conventional commits is something to discuss over there.

I tried to create a sample project:

```
#!/bin/bash
git init . 
git commit --allow-empty -m 'feat: initial'
git tag v0.1.0

git checkout -b feat/a
git commit --allow-empty -m 'feat: a'
git checkout main
git merge --no-ff --edit feat/a # edited to `feat: merge branch 'feat/a'`

git tag "v$(convco version --bump)"
```

The resulting git log is:

```
❯ git log --oneline --graph
*   d954b5d (HEAD -> main, tag: v0.1.1) feat: merge branch 'feat/a'
|\  
| * 82f6080 (feat/a) feat: a
|/  
* c4c3d5f (tag: v0.1.0) feat: initial
```

If convco includes the merge commit the changelog is:

```
❯ convco changelog -n --merges
# Changelog

### v0.1.1 (2022-06-29)

#### Features

* merge branch 'feat/a'
  (d954b5d)
* a
  (82f6080)

## v0.1.0 (2022-06-29)

### Features

* initial
  (c4c3d5f)
```

Is that how you want to use it?

**Comment by MAHDTech** [comment]
In your example given above, should it not have been `0.2.0` as doesn't the addition of a feature `feat:  merge branch` increment `MINOR` or have I misunderstood 

>
>feat: a commit of the type feat introduces a new feature to the codebase (this correlates with [MINOR](http://semver.org/#summary) in Semantic Versioning).
>

**Comment by ite-klass** [comment]
I would expect/want the changelog to only include the merge commit, and not the merged commit.

```
# Changelog

### v0.1.1 (2022-06-29)

#### Features

* merge branch 'feat/a'
  (d954b5d)
* a
  (82f6080)

## v0.1.0 (2022-06-29)

### Features

* initial
  (c4c3d5f)
```

Dunno what kind of parameter and parameter names makes most sense for that. Should `--merges` include merge commits, and also merged commits behavior? Or should it include merge commits instead of merged commits?

For me, the merge commit description replaces the merged commits individual descriptions. So that makes most sense to me. Including both seems redundant/duplicated to me.

**Comment by ite-klass** [comment]
A configuration setting for this would be great too. As this is a defined behavior for a repository. It does not really change by invocation.

**Comment by hdevalke** [comment]
I think [`simplify_first_parent`](https://docs.rs/git2/latest/git2/struct.Revwalk.html#method.simplify_first_parent) could be used for that behavior. A config `merges: true` or `--merges` flag can enable this for workflows based on merge commits instead of rebase on main branch.

There is still the case where someone can use merge commits but does want to follow all parents. Another flag `--ignore-merges` could be added  for that case.

**Comment by hdevalke** [comment]
@ite-klass Would you mind to validate #67. Or do you have an example repository where merge commits are following conventional commit message?

**Comment by ite-klass** [comment]
I do no such public repository at hand.

I will take a look at it/test it.

As a side note, it would be helpful if PR or commit messages would include the parameters etc it introduces. Then I would not have to look into and understand the code changes it touches. It’ll also help others looking at the changes.

**Comment by hdevalke** [comment]
I tested it out on the simple script above. 
The results:

```
❯ ../target/debug/convco changelog --merges --simplify-first-parent
# Changelog

### [v0.1.1](///compare/v0.1.0...v0.1.1) (2022-07-05)

#### Features

* merge branch 'feat/a
  (4773727)

## v0.1.0 (2022-07-05)

### Features

* initial
  (4174c64)

❯ ../target/debug/convco changelog --merges
# Changelog

### [v0.1.1](///compare/v0.1.0...v0.1.1) (2022-07-05)

#### Features

* merge branch 'feat/a
  (4773727)
* a
  (5d9484a)

## v0.1.0 (2022-07-05)

### Features

* initial
  (4174c64)

❯ ../target/debug/convco changelog --simplify-first-parent
# Changelog

### [v0.1.1](///compare/v0.1.0...v0.1.1) (2022-07-05)

## v0.1.0 (2022-07-05)

### Features

* initial
  (4174c64)

❯ ../target/debug/convco changelog
# Changelog

### [v0.1.1](///compare/v0.1.0...v0.1.1) (2022-07-05)

#### Features

* a
  (5d9484a)

## v0.1.0 (2022-07-05)

### Features

* initial
  (4174c64)

```

For your workflow probably `--merges --simplify-first-parent` is what you need. The flags can be set in the .versionrc too:

```
❯ cat <<'EOT' > .versionrc
∙ merges: true
∙ simplifyFirstParent: true
∙ EOT

❯ ../target/debug/convco changelog
# Changelog

### [v0.1.1](///compare/v0.1.0...v0.1.1) (2022-07-05)

#### Features

* merge branch 'feat/a
  (4773727)

## v0.1.0 (2022-07-05)

### Features

* initial
  (4174c64)
```

**Comment by hdevalke** [comment]
I think the two new flags `--merges` and `--first-parent` (also configurable) can be used in the ci pipeline to be flexible with merge commits. If any bug/enhancement is found/wanted please open a new ticket.

**Comment by hdevalke** [comment]
Which channel do you use to install convco? Normally the docker image with tag `latest` contains the current master code.
I was thinking to try to implement some more tickets and release at the end of this week.

**Comment by hdevalke** [comment]
I made a change to trigger manual build of the binaries.
They will be available as build artifacts here: https://github.com/convco/convco/actions/runs/2634913993

**Comment by hdevalke** [comment]
The artifacts are available here: https://github.com/convco/convco/actions/runs/2634913993#artifacts

Until it is released you could use one of the binaries from there

**Comment by ite-klass** [comment]
Thank you.

I will wait for a versioned release before deploying to CI and announcing to colleagues though.

**Comment by hdevalke** [comment]
v0.3.11 has been released.
