### ISSUE TITLE
Add release (PRs,MRs) workflows

### ISSUE THREAD

**Issue by vincent-herlemont** [convco/convco#73]
It could be interesting if `convco` supports release PRs workflow like [googleapis/release-please](https://github.com/googleapis/release-please) but which support more provide than GitHub. Like GitLab, Bitbucket.

Naiv example, to run in GitLab CI:
```bash
convco release \
   --provider gitlab \
   --url https://<API URL>
```

Like `release-please` for GitHub the above command creates:
- Create/Update a new branch (`release-branch`)
- Create/Update an MR on GitLab.
- Create/Update the changelog in the MR description issue.
<img width="698" alt="screen" src="https://user-images.githubusercontent.com/5569193/181191434-57befa62-54a3-4026-b4ce-8616e4012a70.png">

---

NOTICE: I working for [aerys](https://github.com/aerys) and we would be interested to improve [convco](https://github.com/convco/convco) with you.

**Comment by hdevalke** [comment]
Thanks you for this proposal.

The idea of `convco` is to be independant of the build tools/cicd environment and have no runtime dependencies.

The version update can be done like this for some programming languages:

```
# rust
cargo release $(convco version --bump)
# java
mvn versions:set -DnewVersion=$(convco version --bump)
# javascript
npm version $(convco version --bump)
# git
git tag v$(convco version --bump)
```

`convco release` could run this + creating a changelog. 

To create pull requests, I don't know what would be the best option to implement it. 
Probably a custom command configurable by the user. 
For example for gitlab provide [extra options](https://docs.gitlab.com/ee/user/project/push_options.html) to `git push`.
For gitlab/bitbucket, i don't know if they have similar options.

Any help implementing this is welcome, but first it should be clear what is expected from this new subcommand.

**Comment by hdevalke** [comment]
@vincent-herlemont Could you define an MVP?

e.g. which host (github/gitlab/bitbucket), which project type (maven/node/cargo)?

**Comment by hdevalke** [comment]
@vincent-herlemont Are you still interested in a `convco release` command?
I think it will be complex to implement as aside from knowing different providers apis, it also needs to know how to update versions in different packagers for different languages.

**Comment by hdevalke** [comment]
I will close this as it will add a lot of complexity. If you have a proposal you can reopen an issue or create a pull request.
