### ISSUE TITLE
Auto pass commit message generated by `git revert` or github PR revert feature

### ISSUE THREAD

**Issue by liufuyang** [convco/convco#80]
## Is your feature request related to a problem? Please describe.

Hi there, we use convco in our build system it mostly work well, but sometimes we thought it might be nice to still use github UI's button to revert a PR, as the `git revert` creates a message like
`Revert "chore(xx): some old commits"`

So we get errors like this:
```
[convco-check] FAIL  c2ea809  first line doesn't match `<type>[optional scope]: <description>`  Revert "chore(cloud-run): reduce pod cpu...
```

---

## Describe the solution you'd like

* It would be nice, perhaps by default a message like `Revert "chore(xx): some old commits"`
can also pass the check? Or make some way of turning on this config very easily?

As this commit is generated by running `git revert` or by clicking github `Revert` PR button. We build CI with github PRs so we hope to allow fast rollback when things go wrong via clicking the github `Revert` PR button.

Currently looking at the convco config doc I am confused and not sure how we could just allow this special `Revert "<some_good_old_commit>"` to pass check as well.

---

## Describe alternatives you've considered

Seems no way to hack git/github to generate a revert commit message in the conventional commit message format.

---

## Additional context
Step 1: clicking this on github:
<img width="372" alt="image" src="https://user-images.githubusercontent.com/161689/191772636-e7686b8d-26a4-47d4-b154-e5d90c329cfd.png">
And CI failed:
<img width="1004" alt="image" src="https://user-images.githubusercontent.com/161689/191772799-32047fbe-8a29-422d-9dc6-ade629b74995.png">

**Comment by liufuyang** [comment]
Oh, by the way, thanks for creating a nice tool here and using Rust for this 😄🦀

**Comment by liufuyang** [comment]
Yep, sounds like a flag would be the simplest thing for us, but providing a `.versionrc` file option could be nice as well.

Mind if I ask why the config file is called `.versionrc` but not something like `.convcorc`? 😄 

Also, how much work there is to add an extra flag? I knew a bit of Rust, perhaps I could help a bit? But I am very bad at regular expression.

**Comment by hdevalke** [comment]
It is based on the conventional changelog file see [here](https://github.com/convco/convco/blob/master/src/conventional/config.rs#L26). The idea was to be able replace it with convco, without adding another file.

You can have a look at cb508c6a40a12d77129ec4de461677383a84d704 where 3 new flags are added. I think this is a simple change. You're welcome to help.

**Comment by liufuyang** [comment]
Thanks, great, I will give it a try later, if confused, will let you know :)

**Comment by liufuyang** [comment]
@hdevalke I made a simple implementation with a bool `--ignore-reverts`. I guess this is probably good enough as I feel in reality perhaps many others will try to go config the matching regex to match on revert messages. Initially, I tried to use `--ignore-reverts [pattern]` with default pattern `(?i)revert`, but I realize this will make this option turned on by default. Perhaps that is not a good idea? Making it as a bool (false by default) at least will not change the current behavior if this option is not used explicitly.

Let me know what you think :)

**Comment by hdevalke** [comment]
@liufuyang Thank you for the PR.

You could have used `Option<Option<Regex>>` as type to make the difference between provided with no arg `Some(None)`, provided with an arg `Some(Some(regex))` or not provided (`None`). But the boolean approach is good enough to start with. See https://github.com/convco/convco/pull/81#discussion_r979259067

**Comment by liufuyang** [comment]
Thanks, I see. Aha, `Option<Option<Regex>>` sounds like one way of doing it. I addressed your input on the PR, so for now still using a simple bool and the code is simpler now to just checking the start with `Revert "`.

**Comment by hdevalke** [comment]
Maybe just one remark: if you revert a feature and ignore the check, the generated changelog will contain the feature even if it has been reverted.

**Comment by liufuyang** [comment]
Thanks, that is good to know. I think this is mostly for our internal backend services. The changelog is not really that important there. For maintained internal/external libraries, we could choose to manually revert and not really on this git revert generated messages 👍
