### ISSUE TITLE
Request for Changelog

### ISSUE THREAD

**Issue by sgriffith3** [convco/convco#85]
**Is your feature request related to a problem? Please describe.**
There was a recent change to git (involving safe directory) that I wanted to investigate, so I came to examine what changed with the last release. To my dismay, there was no CHANGELOG.md.

**Describe the solution you'd like**
I would like to see a CHANGELOG.md file in the repo

**Describe alternatives you've considered**
I ended up just looking at the most recent release.

**Additional context**
It is quite ironic that a tool that makes a changelog does not have a changelog. :smile:

**Comment by hdevalke** [comment]
You can see the changes in the release https://github.com/convco/convco/releases

You are right the tool should generate a changelog when doing a release. There is currently an issue with the rendering in github flavored markdown. I am busy implementing a feature to remove the word-wrap

**Comment by hdevalke** [comment]
I added a changelog to the repository. But will keep this ticket open in order to add this to `cargo release` config to automate this.
But I think i need to add an option to add the unreleased commits to the next version or else there will be a `## Unreleased (2022-09-26)` header
