### ISSUE TITLE
Add --safe-directory flag

### ISSUE THREAD

**Issue by sgriffith3** [convco/convco#86]
**Is your feature request related to a problem? Please describe.**
My team has been struggling to get the newest release (0.3.12) to work inside of a Jenkins environment, that then launches the convco container with docker.

Running this command:

`docker run -v "$PWD:/tmp" --workdir /tmp --rm convco`

We have been seeing the error: 

`Error: Git(Error { code: -3, klass: 7, message: "config value 'safe.directory' was not found" })` 

While this would regularly be overcome easily with the command `git config --add safe.directory *`, this is unfortunately not an option for the docker container as far as we have figured out.

**Describe the solution you'd like**
I would like an easy way to add a safe-directory. I believe this could be achieved with convco updating the configuration of git, and therefore suggest adding an optional flag that would temporarily add a specified safe directory.

**Describe alternatives you've considered**
Our workaround to this was to create a **gitconfig** file, and mount that as a volume.

```
# gitconfig
[safe]
  directory=/tmp
```

Working command:
`docker run --rm -v "$PWD:/tmp" -v "$PWD/gitconfig:/etc/gitconfig" -w /tmp convco version`

**Additional context**
If this is not possible for the time being, a note in the README indicating this workaround would be nice.

**Comment by hdevalke** [comment]
I had to lookup what this safe directory is doing:

> https://git-scm.com/docs/git-config/2.35.2#Documentation/git-config.txt-safedirectory
> These config entries specify Git-tracked directories that are considered safe even if they are owned by someone other than the current user. 

is it possible the directory `/tmp` is not owned by the user running docker (i guess root is running in your example, but the pwd is owned by the jenkins user. `docker run -u "$(id -u):$(id -g)" -v "$PWD:/tmp" --workdir /tmp --rm convco` could probably solve your issue as well.

The issue with `*` is probably related to https://github.com/libgit2/libgit2/issues/6391.

**Comment by hdevalke** [comment]
#88 adds better error handling for this case.

If it occurs you will see this in the stderr output:

```
Error: Could not open the git repository.
If run from docker set the right user id and group id.
E.g. `docker run -u "$(id -u):$(id -g)" -v "$PWD:/tmp" --workdir /tmp --rm convco/convco`

Caused by:
    config value 'safe.directory' was not found; class=Config (7); code=NotFound (-3)
```
